version: '3.9'

# extension field: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-networks: &networks
  networks:
    - ac-network

x-build-params: &build-params
  context: .
  dockerfile: ./apps/docker/Dockerfile
  args:
    USER_ID: ${DOCKER_USER_ID:-1000}
    GROUP_ID: ${DOCKER_GROUP_ID:-1000}
    DOCKER_USER: ${DOCKER_USER:-acore}
    # BUILDKIT_INLINE_CACHE: 1
  cache_from:
    - acore/ac-wotlk-authserver:${DOCKER_IMAGE_TAG:-master}
    - acore/ac-wotlk-authserver-local:${DOCKER_IMAGE_TAG:-master}
    - acore/ac-wotlk-worldserver:${DOCKER_IMAGE_TAG:-master}
    - acore/ac-wotlk-worldserver-local:${DOCKER_IMAGE_TAG:-master}
    - acore/ac-wotlk-dev-server:${DOCKER_IMAGE_TAG:-master}
    - acore/ac-wotlk-tools:${DOCKER_IMAGE_TAG:-master}
    # Need to fix reduced space on GH actions first
    # - acore/ac-wotlk-client-data:${DOCKER_IMAGE_TAG:-master}

x-ac-shared-conf: &ac-shared-conf
  <<: *networks
  working_dir: /azerothcore
  environment:
    AC_DISABLE_INTERACTIVE: "1"

x-ac-service-conf: &ac-service-conf
  <<: *ac-shared-conf
  # List can't be merged. See: https://forums.docker.com/t/how-to-merge-a-list-of-volumes-from-an-extension-field-into-the-service-definition/77454
  # volumes:
  #   - ${DOCKER_VOL_ETC:-./env/docker/etc}:/azerothcore/env/dist/etc
  #   # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
  #   - ${DOCKER_VOL_LOGS:-./env/docker/logs}:/azerothcore/env/dist/logs:delegated


services: 

  ac-database:
    <<: *networks
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 40
 
  ac-db-import:
    <<: *ac-shared-conf
    image: acore/ac-wotlk-worldserver-local:${DOCKER_IMAGE_TAG:-master} # name of the generated image after built locally
    command: ./env/dist/bin/dbimport
    volumes:
      # read-only binaries compiled by ac-dev-server
      - ${DOCKER_VOL_BIN:-ac-bin-dev}:/azerothcore/env/dist/bin:ro
      - ${DOCKER_VOL_ETC:-./env/docker/etc}:/azerothcore/env/dist/etc
      # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
      - ${DOCKER_VOL_LOGS:-./env/docker/logs}:/azerothcore/env/dist/logs:delegated
    profiles: [local, app, db-import-local]
    depends_on:
      ac-database:
        condition: service_healthy
 
volumes:
  ac-database: 
  ac-bin-dev: 

networks:
  ac-network:
